name: Keep Server Alive

on:
  schedule:
    # Run every 10 minutes during active hours (UTC)
    # This covers most time zones when users might be active
    - cron: '*/10 6-22 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Backend Server
        run: |
          echo "Pinging backend server to keep it alive..."
          curl -f -s -o /dev/null -w "Status: %{http_code}, Time: %{time_total}s\n" \
            -H "User-Agent: GitHub-KeepAlive/1.0" \
            "${{ secrets.BACKEND_URL }}/health" || echo "Ping failed, server might be starting up"
          
      - name: Wait and ping again
        run: |
          echo "Waiting 30 seconds and pinging again to ensure server is warm..."
          sleep 30
          curl -f -s -o /dev/null -w "Status: %{http_code}, Time: %{time_total}s\n" \
            -H "User-Agent: GitHub-KeepAlive/1.0" \
            "${{ secrets.BACKEND_URL }}/health" || echo "Second ping failed"
